/*
 * Splash.java
 *
 * Created on February 4, 2008, 8:57 PM
 */

package voterrecord;
import java.util.*;
import java.awt.event.*;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author  salamsm
 */
public class Splash extends javax.swing.JFrame {
    
    /** Creates new form Splash */
    public Splash() {
              
        initComponents();
        
        Dimension prefsize = new Dimension(591,250);
        setPreferredSize(prefsize);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension labelSize = prefsize;
        setLocation(screenSize.width/2 - (labelSize.width/2),screenSize.height/2 - (labelSize.height/2));
        show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfStatus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VRMS 1.0.0");
        setBounds(new java.awt.Rectangle(400, 300, 0, 0));
        setEnabled(false);
        setResizable(false);
        setUndecorated(true);
        jPanel1.setBackground(new java.awt.Color(175, 86, 103));
        jPanel1.setPreferredSize(new java.awt.Dimension(517, 300));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\vrms\\images\\progress.gif"));
        jLabel1.setIconTextGap(0);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\vrms\\images\\vrms2.jpg"));
        jLabel2.setIconTextGap(0);

        tfStatus.setBackground(new java.awt.Color(175, 86, 103));
        tfStatus.setEditable(false);
        tfStatus.setBorder(null);
        tfStatus.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tfStatus.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11));
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Loading VRMS Version 1.0.0 .......");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Copyright (C) 2007-2008 Intelligent Software Systems ISS Labs");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addComponent(jLabel1))))
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel4)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }
    
    
    public void executeMessages(){
        
        String javaVM_name = System.getProperty("java.vm.name");
        String info = "Searching for Java Virtual Machine....";
        showMessage(info,1);
        String java_version = System.getProperty("java.version");
        info = "Java VM Foun - Specification name: "+javaVM_name;
        showMessage(info,2);
        info = "Searching for java virtual machine version.........";
        showMessage(info,2);
        info = "Java VM Version is : "+java_version;
        showMessage(info,2);
        info = "Determining class format for java vm...";
        showMessage(info,2);
        String classFormatVersion = System.getProperty("java.class.version");
        info = "Java class format version is : "+classFormatVersion;
        showMessage(info,2);
        String os = System.getProperty("os.name");
        info = "Determining the type of underlying operating system.....";
        showMessage(info,2);
        info = "Operating system is: "+os;
        showMessage(info,2);
        info = "Determining operating system version....";
        String os_version = System.getProperty("os.version");
        info = "Opeating system version is : "+os_version;
        showMessage(info,2);
        String userName = System.getProperty("user.name");
        info = "Preparing to start transaction with user "+userName;
        System.out.println("4");
        showMessage(info,2);
        showMessage("system parameters are currently read..this may take several minutes",2);
        readParameters();
        System.out.println("5");
        showMessage("Activating user authentication: ",2);
        showMessage("",2);
        stopExecution();
    }
    
    public void stopExecution(){
            System.out.println("Stop execution method activated!");
            this.setVisible(false);
            System.out.println("Visible method is set to false!");
            this.dispose();
            System.out.println("System is instructed to destroy itself!");
        
        
    }
    
      
    public void showMessage(String message, int time){
        
        tfStatus.setText(message);
        
        try
        {
            Thread.currentThread().sleep(1000);
        }
        catch(Exception e)
        {
            System.out.println("This is not to be things");
        }
        
    }
    
    
    public void readParameters()
    {
        NetworkInfo ni = new NetworkInfo();
        String windowsPID = "";
        String systemPhysicalAddr = "";
        try{windowsPID = ni.windowsProductID();}catch(Exception e){JOptionPane.showMessageDialog(null,"Unable to read system\nEither information lost\nor system not registered to use software");}
        if(windowsPID.compareTo(SystemConstants.PARAMETER_OS_SR_NO_REG_1)==0)
            ;
        else{
            JOptionPane.showMessageDialog(null,"System not registered to use this software","ERROR",JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
        
        try{systemPhysicalAddr = ni.getMacAddress();}catch(Exception e){JOptionPane.showMessageDialog(null,"Unable to read system\nEither information lost\nor system not registered to use software");}
        
        if(systemPhysicalAddr.compareTo(SystemConstants.PARAMETER_SYSTEM_PHYSICAL_ADDR_1)==0)
            ;
        else{
            JOptionPane.showMessageDialog(null,"System not registered to use this software","ERROR",JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }        
        
    }
    
    
    public void clearStatus(){
        tfStatus.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfStatus;
    // End of variables declaration//GEN-END:variables
    
}
